name: evmap
description: "A visually rich and animated EV charging station finder app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ADD THESE for maps and API calls
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.1.0


 

  # Your existing dependencies
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true